### ISSUE TITLE
MySQL that makes the server to die

### ISSUE THREAD

**Issue by tkumark** [Xeoncross/xeoncross#1]
Sorry to trouble you where you able to find solution to this issues. I am facing he same issue but not able to find a solution. I have a very simple table with no Foreign Keys

https://gist.github.com/Xeoncross/900ed9d1cdf3301707347f6f603b1205#file-2-percona-toolkit-md

**Comment by Xeoncross** [comment]
I ended up using https://github.com/github/gh-ost/ for the last large migration I remember around that time.
